-- Стейтове за всяка държава
INSERT INTO states (name, country_id) VALUES
-- Afghanistan
('Badakhshan', (SELECT id FROM countries WHERE code = 'AF')),
('Badghis', (SELECT id FROM countries WHERE code = 'AF')),
('Baghlan', (SELECT id FROM countries WHERE code = 'AF')),
('Balkh', (SELECT id FROM countries WHERE code = 'AF')),
('Bamyan', (SELECT id FROM countries WHERE code = 'AF')),
-- Albania
('Berat', (SELECT id FROM countries WHERE code = 'AL')),
('Dibër', (SELECT id FROM countries WHERE code = 'AL')),
('Durrës', (SELECT id FROM countries WHERE code = 'AL')),
('Elbasan', (SELECT id FROM countries WHERE code = 'AL')),
('Fier', (SELECT id FROM countries WHERE code = 'AL')),
-- Algeria
('Adrar', (SELECT id FROM countries WHERE code = 'DZ')),
('Chlef', (SELECT id FROM countries WHERE code = 'DZ')),
('Laghouat', (SELECT id FROM countries WHERE code = 'DZ')),
('Oum El Bouaghi', (SELECT id FROM countries WHERE code = 'DZ')),
('Batna', (SELECT id FROM countries WHERE code = 'DZ')),
-- Andorra
('Andorra la Vella', (SELECT id FROM countries WHERE code = 'AD')),
-- Angola
('Bengo', (SELECT id FROM countries WHERE code = 'AO')),
('Benguela', (SELECT id FROM countries WHERE code = 'AO')),
('Bié', (SELECT id FROM countries WHERE code = 'AO')),
('Cabinda', (SELECT id FROM countries WHERE code = 'AO')),
('Cuando Cubango', (SELECT id FROM countries WHERE code = 'AO')),
-- Antigua and Barbuda
('Saint George', (SELECT id FROM countries WHERE code = 'AG')),
('Saint John', (SELECT id FROM countries WHERE code = 'AG')),
('Saint Mary', (SELECT id FROM countries WHERE code = 'AG')),
('Saint Paul', (SELECT id FROM countries WHERE code = 'AG')),
('Saint Peter', (SELECT id FROM countries WHERE code = 'AG')),
-- Argentina
('Buenos Aires', (SELECT id FROM countries WHERE code = 'AR')),
('Catamarca', (SELECT id FROM countries WHERE code = 'AR')),
('Chaco', (SELECT id FROM countries WHERE code = 'AR')),
('Chubut', (SELECT id FROM countries WHERE code = 'AR')),
('Córdoba', (SELECT id FROM countries WHERE code = 'AR')),
-- Armenia
('Aragatsotn', (SELECT id FROM countries WHERE code = 'AM')),
('Ararat', (SELECT id FROM countries WHERE code = 'AM')),
('Armavir', (SELECT id FROM countries WHERE code = 'AM')),
('Gegharkunik', (SELECT id FROM countries WHERE code = 'AM')),
('Kotayk', (SELECT id FROM countries WHERE code = 'AM')),
-- Australia
('New South Wales', (SELECT id FROM countries WHERE code = 'AU')),
('Victoria', (SELECT id FROM countries WHERE code = 'AU')),
('Queensland', (SELECT id FROM countries WHERE code = 'AU')),
('Western Australia', (SELECT id FROM countries WHERE code = 'AU')),
('South Australia', (SELECT id FROM countries WHERE code = 'AU')),
-- Austria
('Burgenland', (SELECT id FROM countries WHERE code = 'AT')),
('Carinthia', (SELECT id FROM countries WHERE code = 'AT')),
('Lower Austria', (SELECT id FROM countries WHERE code = 'AT')),
('Upper Austria', (SELECT id FROM countries WHERE code = 'AT')),
('Salzburg', (SELECT id FROM countries WHERE code = 'AT')),
-- Azerbaijan
('Absheron', (SELECT id FROM countries WHERE code = 'AZ')),
('Ganja-Gazakh', (SELECT id FROM countries WHERE code = 'AZ')),
('Guba-Khachmaz', (SELECT id FROM countries WHERE code = 'AZ')),
('Lankaran', (SELECT id FROM countries WHERE code = 'AZ')),
('Shaki-Zaqatala', (SELECT id FROM countries WHERE code = 'AZ')),
-- Bahamas
('Acklins', (SELECT id FROM countries WHERE code = 'BS')),
('Berry Islands', (SELECT id FROM countries WHERE code = 'BS')),
('Bimini', (SELECT id FROM countries WHERE code = 'BS')),
('Black Point', (SELECT id FROM countries WHERE code = 'BS')),
('Cat Island', (SELECT id FROM countries WHERE code = 'BS')),
-- Bahrain
('Capital Governorate', (SELECT id FROM countries WHERE code = 'BH')),
('Central Governorate', (SELECT id FROM countries WHERE code = 'BH')),
('Muharraq Governorate', (SELECT id FROM countries WHERE code = 'BH')),
('Northern Governorate', (SELECT id FROM countries WHERE code = 'BH')),
('Southern Governorate', (SELECT id FROM countries WHERE code = 'BH')),
-- Bangladesh
('Barisal Division', (SELECT id FROM countries WHERE code = 'BD')),
('Chittagong Division', (SELECT id FROM countries WHERE code = 'BD')),
('Dhaka Division', (SELECT id FROM countries WHERE code = 'BD')),
('Khulna Division', (SELECT id FROM countries WHERE code = 'BD')),
('Rajshahi Division', (SELECT id FROM countries WHERE code = 'BD')),
-- Barbados
('Christ Church', (SELECT id FROM countries WHERE code = 'BB')),
('Saint Andrew', (SELECT id FROM countries WHERE code = 'BB')),
('Saint George', (SELECT id FROM countries WHERE code = 'BB')),
('Saint James', (SELECT id FROM countries WHERE code = 'BB')),
('Saint John', (SELECT id FROM countries WHERE code = 'BB')),
-- Belarus
('Brest Region', (SELECT id FROM countries WHERE code = 'BY')),
('Gomel Region', (SELECT id FROM countries WHERE code = 'BY')),
('Grodno Region', (SELECT id FROM countries WHERE code = 'BY')),
('Minsk Region', (SELECT id FROM countries WHERE code = 'BY')),
('Mogilev Region', (SELECT id FROM countries WHERE code = 'BY')),
-- Belgium
('Brussels Capital Region', (SELECT id FROM countries WHERE code = 'BE')),
('Flanders', (SELECT id FROM countries WHERE code = 'BE')),
('Wallonia', (SELECT id FROM countries WHERE code = 'BE')),
-- Belize
('Belize District', (SELECT id FROM countries WHERE code = 'BZ')),
('Cayo District', (SELECT id FROM countries WHERE code = 'BZ')),
('Corozal District', (SELECT id FROM countries WHERE code = 'BZ')),
('Orange Walk District', (SELECT id FROM countries WHERE code = 'BZ')),
('Stann Creek District', (SELECT id FROM countries WHERE code = 'BZ')),
-- Benin
('Alibori', (SELECT id FROM countries WHERE code = 'BJ')),
('Atakora', (SELECT id FROM countries WHERE code = 'BJ')),
('Atlantique', (SELECT id FROM countries WHERE code = 'BJ')),
('Borgou', (SELECT id FROM countries WHERE code = 'BJ')),
('Collines', (SELECT id FROM countries WHERE code = 'BJ')),
-- Bhutan
('Bumthang', (SELECT id FROM countries WHERE code = 'BT')),
('Chhukha', (SELECT id FROM countries WHERE code = 'BT')),
('Dagana', (SELECT id FROM countries WHERE code = 'BT')),
('Gasa', (SELECT id FROM countries WHERE code = 'BT')),
('Haa', (SELECT id FROM countries WHERE code = 'BT')),
-- Bolivia
('Chuquisaca', (SELECT id FROM countries WHERE code = 'BO')),
('Cochabamba', (SELECT id FROM countries WHERE code = 'BO')),
('Beni', (SELECT id FROM countries WHERE code = 'BO')),
('La Paz', (SELECT id FROM countries WHERE code = 'BO')),
('Oruro', (SELECT id FROM countries WHERE code = 'BO')),
-- Bosnia and Herzegovina
('Una-Sana', (SELECT id FROM countries WHERE code = 'BA')),
('Posavina', (SELECT id FROM countries WHERE code = 'BA')),
('Tuzla', (SELECT id FROM countries WHERE code = 'BA')),
('Zenica-Doboj', (SELECT id FROM countries WHERE code = 'BA')),
('Sarajevo', (SELECT id FROM countries WHERE code = 'BA')),
-- Botswana
('Central District', (SELECT id FROM countries WHERE code = 'BW')),
('Ghanzi District', (SELECT id FROM countries WHERE code = 'BW')),
('Kgalagadi District', (SELECT id FROM countries WHERE code = 'BW')),
('Kgatleng District', (SELECT id FROM countries WHERE code = 'BW')),
('Kweneng District', (SELECT id FROM countries WHERE code = 'BW')),
-- Brazil
('Acre', (SELECT id FROM countries WHERE code = 'BR')),
('Alagoas', (SELECT id FROM countries WHERE code = 'BR')),
('Amapá', (SELECT id FROM countries WHERE code = 'BR')),
('Amazonas', (SELECT id FROM countries WHERE code = 'BR')),
('Bahia', (SELECT id FROM countries WHERE code = 'BR')),
-- Brunei
('Belait', (SELECT id FROM countries WHERE code = 'BN')),
('Brunei-Muara', (SELECT id FROM countries WHERE code = 'BN')),
('Temburong', (SELECT id FROM countries WHERE code = 'BN')),
('Tutong', (SELECT id FROM countries WHERE code = 'BN')),
-- Bulgaria
('Blagoevgrad', (SELECT id FROM countries WHERE code = 'BG')),
('Burgas', (SELECT id FROM countries WHERE code = 'BG')),
('Dobrich', (SELECT id FROM countries WHERE code = 'BG')),
('Gabrovo', (SELECT id FROM countries WHERE code = 'BG')),
('Haskovo', (SELECT id FROM countries WHERE code = 'BG')),
-- Burkina Faso
('Boucle du Mouhoun', (SELECT id FROM countries WHERE code = 'BF')),
('Cascades', (SELECT id FROM countries WHERE code = 'BF')),
('Centre', (SELECT id FROM countries WHERE code = 'BF')),
('Centre-Est', (SELECT id FROM countries WHERE code = 'BF')),
('Centre-Nord', (SELECT id FROM countries WHERE code = 'BF')),
-- Burundi
('Bubanza', (SELECT id FROM countries WHERE code = 'BI')),
('Bujumbura Mairie', (SELECT id FROM countries WHERE code = 'BI')),
('Bujumbura Rural', (SELECT id FROM countries WHERE code = 'BI')),
('Bururi', (SELECT id FROM countries WHERE code = 'BI')),
('Cankuzo', (SELECT id FROM countries WHERE code = 'BI')),
-- Cabo Verde
('Boa Vista', (SELECT id FROM countries WHERE code = 'CV')),
('Brava', (SELECT id FROM countries WHERE code = 'CV')),
('Maio', (SELECT id FROM countries WHERE code = 'CV')),
('Mosteiros', (SELECT id FROM countries WHERE code = 'CV')),
('Paul', (SELECT id FROM countries WHERE code = 'CV')),
-- Cambodia
('Banteay Meanchey', (SELECT id FROM countries WHERE code = 'KH')),
('Battambang', (SELECT id FROM countries WHERE code = 'KH')),
('Kampong Cham', (SELECT id FROM countries WHERE code = 'KH')),
('Kampong Chhnang', (SELECT id FROM countries WHERE code = 'KH')),
('Kampong Speu', (SELECT id FROM countries WHERE code = 'KH')),
-- Cameroon
('Adamawa', (SELECT id FROM countries WHERE code = 'CM')),
('Centre', (SELECT id FROM countries WHERE code = 'CM')),
('East', (SELECT id FROM countries WHERE code = 'CM')),
('Far North', (SELECT id FROM countries WHERE code = 'CM')),
('Littoral', (SELECT id FROM countries WHERE code = 'CM')),
-- Canada
('Alberta', (SELECT id FROM countries WHERE code = 'CA')),
('British Columbia', (SELECT id FROM countries WHERE code = 'CA')),
('Manitoba', (SELECT id FROM countries WHERE code = 'CA')),
('New Brunswick', (SELECT id FROM countries WHERE code = 'CA')),
('Newfoundland and Labrador', (SELECT id FROM countries WHERE code = 'CA')),
-- Central African Republic
('Bamingui-Bangoran', (SELECT id FROM countries WHERE code = 'CF')),
('Bangui', (SELECT id FROM countries WHERE code = 'CF')),
('Basse-Kotto', (SELECT id FROM countries WHERE code = 'CF')),
('Haute-Kotto', (SELECT id FROM countries WHERE code = 'CF')),
('Haut-Mbomou', (SELECT id FROM countries WHERE code = 'CF')),
-- Chad
('Bahr el Gazel', (SELECT id FROM countries WHERE code = 'TD')),
('Batha', (SELECT id FROM countries WHERE code = 'TD')),
('Borkou', (SELECT id FROM countries WHERE code = 'TD')),
('Chari-Baguirmi', (SELECT id FROM countries WHERE code = 'TD')),
('Ennedi', (SELECT id FROM countries WHERE code = 'TD')),
-- Chile
('Aisén Region', (SELECT id FROM countries WHERE code = 'CL')),
('Antofagasta Region', (SELECT id FROM countries WHERE code = 'CL')),
('Araucanía Region', (SELECT id FROM countries WHERE code = 'CL')),
('Atacama Region', (SELECT id FROM countries WHERE code = 'CL')),
('Bío Bío Region', (SELECT id FROM countries WHERE code = 'CL')),
-- China
('Anhui', (SELECT id FROM countries WHERE code = 'CN')),
('Beijing', (SELECT id FROM countries WHERE code = 'CN')),
('Chongqing', (SELECT id FROM countries WHERE code = 'CN')),
('Fujian', (SELECT id FROM countries WHERE code = 'CN')),
('Gansu', (SELECT id FROM countries WHERE code = 'CN')),
-- Colombia
('Amazonas', (SELECT id FROM countries WHERE code = 'CO')),
('Antioquia', (SELECT id FROM countries WHERE code = 'CO')),
('Arauca', (SELECT id FROM countries WHERE code = 'CO')),
('Atlántico', (SELECT id FROM countries WHERE code = 'CO')),
('Bolívar', (SELECT id FROM countries WHERE code = 'CO')),
-- Comoros
('Anjouan', (SELECT id FROM countries WHERE code = 'KM')),
('Grande Comore', (SELECT id FROM countries WHERE code = 'KM')),
('Mohéli', (SELECT id FROM countries WHERE code = 'KM')),
-- Congo (Congo-Brazzaville)
('Bouenza', (SELECT id FROM countries WHERE code = 'CG')),
('Brazzaville', (SELECT id FROM countries WHERE code = 'CG')),
('Cuvette', (SELECT id FROM countries WHERE code = 'CG')),
('Cuvette-Ouest', (SELECT id FROM countries WHERE code = 'CG')),
('Kouilou', (SELECT id FROM countries WHERE code = 'CG')),
-- Costa Rica
('Alajuela', (SELECT id FROM countries WHERE code = 'CR')),
('Cartago', (SELECT id FROM countries WHERE code = 'CR')),
('Guanacaste', (SELECT id FROM countries WHERE code = 'CR')),
('Heredia', (SELECT id FROM countries WHERE code = 'CR')),
('Limón', (SELECT id FROM countries WHERE code = 'CR')),
-- Croatia
('City of Zagreb', (SELECT id FROM countries WHERE code = 'HR')),
('Bjelovar-Bilogora County', (SELECT id FROM countries WHERE code = 'HR')),
('Brod-Posavina County', (SELECT id FROM countries WHERE code = 'HR')),
('Dubrovnik-Neretva County', (SELECT id FROM countries WHERE code = 'HR')),
('Istria County', (SELECT id FROM countries WHERE code = 'HR')),
-- Cuba
('Artemisa Province', (SELECT id FROM countries WHERE code = 'CU')),
('Camagüey Province', (SELECT id FROM countries WHERE code = 'CU')),
('Ciego de Ávila Province', (SELECT id FROM countries WHERE code = 'CU')),
('Cienfuegos Province', (SELECT id FROM countries WHERE code = 'CU')),
('Granma Province', (SELECT id FROM countries WHERE code = 'CU')),
-- Cyprus
('Famagusta District', (SELECT id FROM countries WHERE code = 'CY')),
('Kyrenia District', (SELECT id FROM countries WHERE code = 'CY')),
('Larnaca District', (SELECT id FROM countries WHERE code = 'CY')),
('Limassol District', (SELECT id FROM countries WHERE code = 'CY')),
('Nicosia District', (SELECT id FROM countries WHERE code = 'CY')),
-- Czechia (Czech Republic)
('Central Bohemian', (SELECT id FROM countries WHERE code = 'CZ')),
('Hradec Králové', (SELECT id FROM countries WHERE code = 'CZ')),
('Karlovy Vary', (SELECT id FROM countries WHERE code = 'CZ')),
('Liberec', (SELECT id FROM countries WHERE code = 'CZ')),
('Moravian-Silesian', (SELECT id FROM countries WHERE code = 'CZ')),
-- Denmark
('Capital Region', (SELECT id FROM countries WHERE code = 'DK')),
('Central Denmark Region', (SELECT id FROM countries WHERE code = 'DK')),
('North Denmark Region', (SELECT id FROM countries WHERE code = 'DK')),
('Region of Southern Denmark', (SELECT id FROM countries WHERE code = 'DK')),
('Zealand', (SELECT id FROM countries WHERE code = 'DK')),
-- Djibouti
('Ali Sabieh Region', (SELECT id FROM countries WHERE code = 'DJ')),
('Arta Region', (SELECT id FROM countries WHERE code = 'DJ')),
('Dikhil Region', (SELECT id FROM countries WHERE code = 'DJ')),
('Obock Region', (SELECT id FROM countries WHERE code = 'DJ')),
('Tadjourah Region', (SELECT id FROM countries WHERE code = 'DJ')),
-- Dominica
('Saint Andrew Parish', (SELECT id FROM countries WHERE code = 'DM')),
('Saint David Parish', (SELECT id FROM countries WHERE code = 'DM')),
('Saint George Parish', (SELECT id FROM countries WHERE code = 'DM')),
('Saint John Parish', (SELECT id FROM countries WHERE code = 'DM')),
('Saint Joseph Parish', (SELECT id FROM countries WHERE code = 'DM')),
-- Dominican Republic
('Distrito Nacional', (SELECT id FROM countries WHERE code = 'DO')),
('Azua', (SELECT id FROM countries WHERE code = 'DO')),
('Baoruco', (SELECT id FROM countries WHERE code = 'DO')),
('Barahona', (SELECT id FROM countries WHERE code = 'DO')),
('Dajabón', (SELECT id FROM countries WHERE code = 'DO')),
-- Ecuador
('Azuay', (SELECT id FROM countries WHERE code = 'EC')),
('Bolívar', (SELECT id FROM countries WHERE code = 'EC')),
('Cañar', (SELECT id FROM countries WHERE code = 'EC')),
('Carchi', (SELECT id FROM countries WHERE code = 'EC')),
('Chimborazo', (SELECT id FROM countries WHERE code = 'EC')),
-- Egypt
('Alexandria Governorate', (SELECT id FROM countries WHERE code = 'EG')),
('Aswan Governorate', (SELECT id FROM countries WHERE code = 'EG')),
('Asyut Governorate', (SELECT id FROM countries WHERE code = 'EG')),
('Beheira Governorate', (SELECT id FROM countries WHERE code = 'EG')),
('Beni Suef Governorate', (SELECT id FROM countries WHERE code = 'EG')),
-- El Salvador
('Ahuachapán Department', (SELECT id FROM countries WHERE code = 'SV')),
('Cabañas Department', (SELECT id FROM countries WHERE code = 'SV')),
('Chalatenango Department', (SELECT id FROM countries WHERE code = 'SV')),
('Cuscatlán Department', (SELECT id FROM countries WHERE code = 'SV')),
('La Libertad Department', (SELECT id FROM countries WHERE code = 'SV')),
-- Equatorial Guinea
('Annobón', (SELECT id FROM countries WHERE code = 'GQ')),
('Bioko Norte', (SELECT id FROM countries WHERE code = 'GQ')),
('Bioko Sur', (SELECT id FROM countries WHERE code = 'GQ')),
('Centro Sur', (SELECT id FROM countries WHERE code = 'GQ')),
('Kié-Ntem', (SELECT id FROM countries WHERE code = 'GQ')),
-- Eritrea
('Anseba', (SELECT id FROM countries WHERE code = 'ER')),
('Debub', (SELECT id FROM countries WHERE code = 'ER')),
('Gash-Barka', (SELECT id FROM countries WHERE code = 'ER')),
('Maekel', (SELECT id FROM countries WHERE code = 'ER')),
('Northern Red Sea', (SELECT id FROM countries WHERE code = 'ER')),
-- Estonia
('Harju County', (SELECT id FROM countries WHERE code = 'EE')),
('Hiiu County', (SELECT id FROM countries WHERE code = 'EE')),
('Ida-Viru County', (SELECT id FROM countries WHERE code = 'EE')),
('Järva County', (SELECT id FROM countries WHERE code = 'EE')),
('Jõgeva County', (SELECT id FROM countries WHERE code = 'EE')),
-- Eswatini (fmr. "Swaziland")
('Hhohho', (SELECT id FROM countries WHERE code = 'SZ')),
('Lubombo', (SELECT id FROM countries WHERE code = 'SZ')),
('Manzini', (SELECT id FROM countries WHERE code = 'SZ')),
('Shiselweni', (SELECT id FROM countries WHERE code = 'SZ')),
-- Ethiopia
('Addis Ababa', (SELECT id FROM countries WHERE code = 'ET')),
('Afar Region', (SELECT id FROM countries WHERE code = 'ET')),
('Amhara Region', (SELECT id FROM countries WHERE code = 'ET')),
('Benishangul-Gumuz Region', (SELECT id FROM countries WHERE code = 'ET')),
('Dire Dawa', (SELECT id FROM countries WHERE code = 'ET')),
-- Fiji
('Central Division', (SELECT id FROM countries WHERE code = 'FJ')),
('Eastern Division', (SELECT id FROM countries WHERE code = 'FJ')),
('Northern Division', (SELECT id FROM countries WHERE code = 'FJ')),
('Western Division', (SELECT id FROM countries WHERE code = 'FJ')),
-- Finland
('Åland Islands', (SELECT id FROM countries WHERE code = 'FI')),
('Central Finland', (SELECT id FROM countries WHERE code = 'FI')),
('Central Ostrobothnia', (SELECT id FROM countries WHERE code = 'FI')),
('Finland Proper', (SELECT id FROM countries WHERE code = 'FI')),
('Kainuu', (SELECT id FROM countries WHERE code = 'FI')),
-- France
('Auvergne-Rhône-Alpes', (SELECT id FROM countries WHERE code = 'FR')),
('Bourgogne-Franche-Comté', (SELECT id FROM countries WHERE code = 'FR')),
('Brittany', (SELECT id FROM countries WHERE code = 'FR')),
('Centre-Val de Loire', (SELECT id FROM countries WHERE code = 'FR')),
('Corsica', (SELECT id FROM countries WHERE code = 'FR')),
-- Gabon
('Estuaire', (SELECT id FROM countries WHERE code = 'GA')),
('Haut-Ogooué', (SELECT id FROM countries WHERE code = 'GA')),
('Moyen-Ogooué', (SELECT id FROM countries WHERE code = 'GA')),
('Ngounié', (SELECT id FROM countries WHERE code = 'GA')),
('Nyanga', (SELECT id FROM countries WHERE code = 'GA')),
-- Gambia
('Banjul', (SELECT id FROM countries WHERE code = 'GM')),
('Central River Division', (SELECT id FROM countries WHERE code = 'GM')),
('Lower River Division', (SELECT id FROM countries WHERE code = 'GM')),
('North Bank Division', (SELECT id FROM countries WHERE code = 'GM')),
('Upper River Division', (SELECT id FROM countries WHERE code = 'GM')),
-- Georgia
('Adjara', (SELECT id FROM countries WHERE code = 'GE')),
('Guria', (SELECT id FROM countries WHERE code = 'GE')),
('Imereti', (SELECT id FROM countries WHERE code = 'GE')),
('Kakheti', (SELECT id FROM countries WHERE code = 'GE')),
('Kvemo Kartli', (SELECT id FROM countries WHERE code = 'GE')),
-- Germany
('Baden-Württemberg', (SELECT id FROM countries WHERE code = 'DE')),
('Bavaria', (SELECT id FROM countries WHERE code = 'DE')),
('Berlin', (SELECT id FROM countries WHERE code = 'DE')),
('Brandenburg', (SELECT id FROM countries WHERE code = 'DE')),
('Bremen', (SELECT id FROM countries WHERE code = 'DE')),
-- Ghana
('Ashanti Region', (SELECT id FROM countries WHERE code = 'GH')),
('Brong-Ahafo Region', (SELECT id FROM countries WHERE code = 'GH')),
('Central Region', (SELECT id FROM countries WHERE code = 'GH')),
('Eastern Region', (SELECT id FROM countries WHERE code = 'GH')),
('Greater Accra Region', (SELECT id FROM countries WHERE code = 'GH')),
-- Greece
('Attica', (SELECT id FROM countries WHERE code = 'GR')),
('Central Greece', (SELECT id FROM countries WHERE code = 'GR')),
('Central Macedonia', (SELECT id FROM countries WHERE code = 'GR')),
('Crete', (SELECT id FROM countries WHERE code = 'GR')),
('East Macedonia and Thrace', (SELECT id FROM countries WHERE code = 'GR')),
-- Grenada
('Saint Andrew', (SELECT id FROM countries WHERE code = 'GD')),
('Saint David', (SELECT id FROM countries WHERE code = 'GD')),
('Saint George', (SELECT id FROM countries WHERE code = 'GD')),
('Saint John', (SELECT id FROM countries WHERE code = 'GD')),
('Saint Mark', (SELECT id FROM countries WHERE code = 'GD')),
-- Guatemala
('Alta Verapaz', (SELECT id FROM countries WHERE code = 'GT')),
('Baja Verapaz', (SELECT id FROM countries WHERE code = 'GT')),
('Chimaltenango', (SELECT id FROM countries WHERE code = 'GT')),
('Chiquimula', (SELECT id FROM countries WHERE code = 'GT')),
('El Progreso', (SELECT id FROM countries WHERE code = 'GT')),
-- Guinea
('Beyla', (SELECT id FROM countries WHERE code = 'GN')),
('Boffa', (SELECT id FROM countries WHERE code = 'GN')),
('Boké', (SELECT id FROM countries WHERE code = 'GN')),
('Conakry', (SELECT id FROM countries WHERE code = 'GN')),
('Coyah', (SELECT id FROM countries WHERE code = 'GN')),
-- Guinea-Bissau
('Bafatá', (SELECT id FROM countries WHERE code = 'GW')),
('Biombo', (SELECT id FROM countries WHERE code = 'GW')),
('Bolama', (SELECT id FROM countries WHERE code = 'GW')),
('Cacheu', (SELECT id FROM countries WHERE code = 'GW')),
('Gabú', (SELECT id FROM countries WHERE code = 'GW')),
-- Guyana
('Barima-Waini', (SELECT id FROM countries WHERE code = 'GY')),
('Cuyuni-Mazaruni', (SELECT id FROM countries WHERE code = 'GY')),
('Demerara-Mahaica', (SELECT id FROM countries WHERE code = 'GY')),
('East Berbice-Corentyne', (SELECT id FROM countries WHERE code = 'GY')),
('Essequibo Islands-West Demerara', (SELECT id FROM countries WHERE code = 'GY')),
-- Haiti
('Artibonite', (SELECT id FROM countries WHERE code = 'HT')),
('Centre', (SELECT id FROM countries WHERE code = 'HT')),
('Grand Anse', (SELECT id FROM countries WHERE code = 'HT')),
('Nippes', (SELECT id FROM countries WHERE code = 'HT')),
('Nord', (SELECT id FROM countries WHERE code = 'HT')),
-- Honduras
('Atlántida', (SELECT id FROM countries WHERE code = 'HN')),
('Choluteca', (SELECT id FROM countries WHERE code = 'HN')),
('Colón', (SELECT id FROM countries WHERE code = 'HN')),
('Comayagua', (SELECT id FROM countries WHERE code = 'HN')),
('Copán', (SELECT id FROM countries WHERE code = 'HN')),
-- Hungary
('Bács-Kiskun', (SELECT id FROM countries WHERE code = 'HU')),
('Baranya', (SELECT id FROM countries WHERE code = 'HU')),
('Békés', (SELECT id FROM countries WHERE code = 'HU')),
('Borsod-Abaúj-Zemplén', (SELECT id FROM countries WHERE code = 'HU')),
('Budapest', (SELECT id FROM countries WHERE code = 'HU')),
-- Iceland
('Capital Region', (SELECT id FROM countries WHERE code = 'IS')),
('Eastern Region', (SELECT id FROM countries WHERE code = 'IS')),
('Northeastern Region', (SELECT id FROM countries WHERE code = 'IS')),
('Northwestern Region', (SELECT id FROM countries WHERE code = 'IS')),
('Southern Peninsula', (SELECT id FROM countries WHERE code = 'IS')),
-- India
('Andaman and Nicobar Islands', (SELECT id FROM countries WHERE code = 'IN')),
('Andhra Pradesh', (SELECT id FROM countries WHERE code = 'IN')),
('Arunachal Pradesh', (SELECT id FROM countries WHERE code = 'IN')),
('Assam', (SELECT id FROM countries WHERE code = 'IN')),
('Bihar', (SELECT id FROM countries WHERE code = 'IN')),
-- Indonesia
('Aceh', (SELECT id FROM countries WHERE code = 'ID')),
('Bali', (SELECT id FROM countries WHERE code = 'ID')),
('Bangka Belitung Islands', (SELECT id FROM countries WHERE code = 'ID')),
('Banten', (SELECT id FROM countries WHERE code = 'ID')),
('Bengkulu', (SELECT id FROM countries WHERE code = 'ID')),
-- Iran
('Alborz Province', (SELECT id FROM countries WHERE code = 'IR')),
('Ardabil Province', (SELECT id FROM countries WHERE code = 'IR')),
('Bushehr Province', (SELECT id FROM countries WHERE code = 'IR')),
('Chaharmahal and Bakhtiari Province', (SELECT id FROM countries WHERE code = 'IR')),
('East Azerbaijan Province', (SELECT id FROM countries WHERE code = 'IR')),
-- Iraq
('Al Anbar Governorate', (SELECT id FROM countries WHERE code = 'IQ')),
('Babylon Governorate', (SELECT id FROM countries WHERE code = 'IQ')),
('Baghdad Governorate', (SELECT id FROM countries WHERE code = 'IQ')),
('Basra Governorate', (SELECT id FROM countries WHERE code = 'IQ')),
('Dhi Qar Governorate', (SELECT id FROM countries WHERE code = 'IQ')),
-- Ireland
('Carlow', (SELECT id FROM countries WHERE code = 'IE')),
('Cavan', (SELECT id FROM countries WHERE code = 'IE')),
('Clare', (SELECT id FROM countries WHERE code = 'IE')),
('Cork', (SELECT id FROM countries WHERE code = 'IE')),
('Donegal', (SELECT id FROM countries WHERE code = 'IE')),
-- Israel
('Central District', (SELECT id FROM countries WHERE code = 'IL')),
('Haifa District', (SELECT id FROM countries WHERE code = 'IL')),
('Jerusalem District', (SELECT id FROM countries WHERE code = 'IL')),
('Northern District', (SELECT id FROM countries WHERE code = 'IL')),
('Southern District', (SELECT id FROM countries WHERE code = 'IL')),
-- Italy
('Abruzzo', (SELECT id FROM countries WHERE code = 'IT')),
('Apulia', (SELECT id FROM countries WHERE code = 'IT')),
('Basilicata', (SELECT id FROM countries WHERE code = 'IT')),
('Calabria', (SELECT id FROM countries WHERE code = 'IT')),
('Campania', (SELECT id FROM countries WHERE code = 'IT')),
-- Jamaica
('Clarendon', (SELECT id FROM countries WHERE code = 'JM')),
('Hanover', (SELECT id FROM countries WHERE code = 'JM')),
('Kingston', (SELECT id FROM countries WHERE code = 'JM')),
('Manchester', (SELECT id FROM countries WHERE code = 'JM')),
('Portland', (SELECT id FROM countries WHERE code = 'JM')),
-- Japan
('Aichi', (SELECT id FROM countries WHERE code = 'JP')),
('Akita', (SELECT id FROM countries WHERE code = 'JP')),
('Aomori', (SELECT id FROM countries WHERE code = 'JP')),
('Chiba', (SELECT id FROM countries WHERE code = 'JP')),
('Ehime', (SELECT id FROM countries WHERE code = 'JP')),
-- Jordan
('Amman Governorate', (SELECT id FROM countries WHERE code = 'JO')),
('Aqaba Governorate', (SELECT id FROM countries WHERE code = 'JO')),
('Balqa Governorate', (SELECT id FROM countries WHERE code = 'JO')),
('Irbid Governorate', (SELECT id FROM countries WHERE code = 'JO')),
('Jerash Governorate', (SELECT id FROM countries WHERE code = 'JO')),
-- Kazakhstan
('Aktobe Region', (SELECT id FROM countries WHERE code = 'KZ')),
('Almaty', (SELECT id FROM countries WHERE code = 'KZ')),
('Almaty Region', (SELECT id FROM countries WHERE code = 'KZ')),
('Aqmola Region', (SELECT id FROM countries WHERE code = 'KZ')),
('Atyrau Region', (SELECT id FROM countries WHERE code = 'KZ')),
-- Kenya
('Baringo County', (SELECT id FROM countries WHERE code = 'KE')),
('Bomet County', (SELECT id FROM countries WHERE code = 'KE')),
('Bungoma County', (SELECT id FROM countries WHERE code = 'KE')),
('Busia County', (SELECT id FROM countries WHERE code = 'KE')),
('Elgeyo-Marakwet County', (SELECT id FROM countries WHERE code = 'KE')),
-- Kiribati
('Gilbert Islands', (SELECT id FROM countries WHERE code = 'KI')),
('Line Islands', (SELECT id FROM countries WHERE code = 'KI')),
('Phoenix Islands', (SELECT id FROM countries WHERE code = 'KI')),
-- Korea, North (North Korea)
('Chagang Province', (SELECT id FROM countries WHERE code = 'KP')),
('Kangwon Province', (SELECT id FROM countries WHERE code = 'KP')),
('North Hamgyong Province', (SELECT id FROM countries WHERE code = 'KP')),
('Pyongyang', (SELECT id FROM countries WHERE code = 'KP')),
('Ryanggang Province', (SELECT id FROM countries WHERE code = 'KP')),
-- Korea, South (South Korea)
('Busan', (SELECT id FROM countries WHERE code = 'KR')),
('Chungcheongbuk-do', (SELECT id FROM countries WHERE code = 'KR')),
('Chungcheongnam-do', (SELECT id FROM countries WHERE code = 'KR')),
('Daegu', (SELECT id FROM countries WHERE code = 'KR')),
('Daejeon', (SELECT id FROM countries WHERE code = 'KR')),
-- Kosovo
('District of Gjakova', (SELECT id FROM countries WHERE code = 'XK')),
('District of Gjilan', (SELECT id FROM countries WHERE code = 'XK')),
('District of Peć', (SELECT id FROM countries WHERE code = 'XK')),
('District of Pristina', (SELECT id FROM countries WHERE code = 'XK')),
('District of Prizren', (SELECT id FROM countries WHERE code = 'XK')),
-- Kuwait
('Ahmadi Governorate', (SELECT id FROM countries WHERE code = 'KW')),
('Farwaniya Governorate', (SELECT id FROM countries WHERE code = 'KW')),
('Hawalli Governorate', (SELECT id FROM countries WHERE code = 'KW')),
('Mubarak Al-Kabeer Governorate', (SELECT id FROM countries WHERE code = 'KW')),
('Capital Governorate', (SELECT id FROM countries WHERE code = 'KW')),
-- Kyrgyzstan
('Batken Region', (SELECT id FROM countries WHERE code = 'KG')),
('Bishkek', (SELECT id FROM countries WHERE code = 'KG')),
('Chuy Region', (SELECT id FROM countries WHERE code = 'KG')),
('Jalal-Abad Region', (SELECT id FROM countries WHERE code = 'KG')),
('Naryn Region', (SELECT id FROM countries WHERE code = 'KG')),
-- Laos
('Attapeu', (SELECT id FROM countries WHERE code = 'LA')),
('Bokeo', (SELECT id FROM countries WHERE code = 'LA')),
('Bolikhamsai', (SELECT id FROM countries WHERE code = 'LA')),
('Champasak', (SELECT id FROM countries WHERE code = 'LA')),
('Houaphanh', (SELECT id FROM countries WHERE code = 'LA')),
-- Latvia
('Daugavpils', (SELECT id FROM countries WHERE code = 'LV')),
('Jelgava', (SELECT id FROM countries WHERE code = 'LV')),
('Jēkabpils', (SELECT id FROM countries WHERE code = 'LV')),
('Jurmala', (SELECT id FROM countries WHERE code = 'LV')),
('Liepāja', (SELECT id FROM countries WHERE code = 'LV')),
-- Lebanon
('Akkar', (SELECT id FROM countries WHERE code = 'LB')),
('Baalbek-Hermel', (SELECT id FROM countries WHERE code = 'LB')),
('Beirut', (SELECT id FROM countries WHERE code = 'LB')),
('Beqaa', (SELECT id FROM countries WHERE code = 'LB')),
('Mount Lebanon Governorate', (SELECT id FROM countries WHERE code = 'LB')),
-- Lesotho
('Berea District', (SELECT id FROM countries WHERE code = 'LS')),
('Butha-Buthe District', (SELECT id FROM countries WHERE code = 'LS')),
('Leribe District', (SELECT id FROM countries WHERE code = 'LS')),
('Mafeteng District', (SELECT id FROM countries WHERE code = 'LS')),
('Maseru District', (SELECT id FROM countries WHERE code = 'LS')),
-- Liberia
('Bomi County', (SELECT id FROM countries WHERE code = 'LR')),
('Bong County', (SELECT id FROM countries WHERE code = 'LR')),
('Gbarpolu County', (SELECT id FROM countries WHERE code = 'LR')),
('Grand Bassa County', (SELECT id FROM countries WHERE code = 'LR')),
('Grand Cape Mount County', (SELECT id FROM countries WHERE code = 'LR')),
-- Libya
('Al Wahat District', (SELECT id FROM countries WHERE code = 'LY')),
('Benghazi', (SELECT id FROM countries WHERE code = 'LY')),
('Butnan District', (SELECT id FROM countries WHERE code = 'LY')),
('Derna District', (SELECT id FROM countries WHERE code = 'LY')),
('Fezzan', (SELECT id FROM countries WHERE code = 'LY')),
-- Liechtenstein
('Balzers', (SELECT id FROM countries WHERE code = 'LI')),
('Eschen', (SELECT id FROM countries WHERE code = 'LI')),
('Gamprin', (SELECT id FROM countries WHERE code = 'LI')),
('Mauren', (SELECT id FROM countries WHERE code = 'LI')),
('Planken', (SELECT id FROM countries WHERE code = 'LI')),
-- Lithuania
('Alytus County', (SELECT id FROM countries WHERE code = 'LT')),
('Kaunas County', (SELECT id FROM countries WHERE code = 'LT')),
('Klaipėda County', (SELECT id FROM countries WHERE code = 'LT')),
('Marijampolė County', (SELECT id FROM countries WHERE code = 'LT')),
('Panevėžys County', (SELECT id FROM countries WHERE code = 'LT')),
-- Luxembourg
('Capellen', (SELECT id FROM countries WHERE code = 'LU')),
('Clervaux', (SELECT id FROM countries WHERE code = 'LU')),
('Diekirch', (SELECT id FROM countries WHERE code = 'LU')),
('Echternach', (SELECT id FROM countries WHERE code = 'LU')),
('Esch-sur-Alzette', (SELECT id FROM countries WHERE code = 'LU')),
-- Madagascar
('Antananarivo Province', (SELECT id FROM countries WHERE code = 'MG')),
('Antsiranana Province', (SELECT id FROM countries WHERE code = 'MG')),
('Fianarantsoa Province', (SELECT id FROM countries WHERE code = 'MG')),
('Mahajanga Province', (SELECT id FROM countries WHERE code = 'MG')),
('Toamasina Province', (SELECT id FROM countries WHERE code = 'MG')),
-- Malawi
('Central Region', (SELECT id FROM countries WHERE code = 'MW')),
('Northern Region', (SELECT id FROM countries WHERE code = 'MW')),
('Southern Region', (SELECT id FROM countries WHERE code = 'MW')),
-- Malaysia
('Johor', (SELECT id FROM countries WHERE code = 'MY')),
('Kedah', (SELECT id FROM countries WHERE code = 'MY')),
('Kelantan', (SELECT id FROM countries WHERE code = 'MY')),
('Kuala Lumpur', (SELECT id FROM countries WHERE code = 'MY')),
('Labuan', (SELECT id FROM countries WHERE code = 'MY')),
-- Maldives
('Alif Dhaal Atoll', (SELECT id FROM countries WHERE code = 'MV')),
('Central Province', (SELECT id FROM countries WHERE code = 'MV')),
('Faafu Atoll', (SELECT id FROM countries WHERE code = 'MV')),
('Gaafu Alif Atoll', (SELECT id FROM countries WHERE code = 'MV')),
('Gnaviyani Atoll', (SELECT id FROM countries WHERE code = 'MV')),
-- Mali
('Bamako', (SELECT id FROM countries WHERE code = 'ML')),
('Gao Region', (SELECT id FROM countries WHERE code = 'ML')),
('Kayes Region', (SELECT id FROM countries WHERE code = 'ML')),
('Mopti Region', (SELECT id FROM countries WHERE code = 'ML')),
('Sikasso Region', (SELECT id FROM countries WHERE code = 'ML')),
-- Malta
('Gozo', (SELECT id FROM countries WHERE code = 'MT')),
('Northern Region', (SELECT id FROM countries WHERE code = 'MT')),
('Southern Region', (SELECT id FROM countries WHERE code = 'MT')),
-- Marshall Islands
('Kwajalein Atoll', (SELECT id FROM countries WHERE code = 'MH')),
('Majuro Atoll', (SELECT id FROM countries WHERE code = 'MH')),
('Ralik Chain', (SELECT id FROM countries WHERE code = 'MH')),
('Ratak Chain', (SELECT id FROM countries WHERE code = 'MH')),
-- Mauritania
('Adrar Region', (SELECT id FROM countries WHERE code = 'MR')),
('Assaba Region', (SELECT id FROM countries WHERE code = 'MR')),
('Brakna Region', (SELECT id FROM countries WHERE code = 'MR')),
('Dakhlet Nouadhibou', (SELECT id FROM countries WHERE code = 'MR')),
('Gorgol Region', (SELECT id FROM countries WHERE code = 'MR')),
-- Mauritius
('Black River District', (SELECT id FROM countries WHERE code = 'MU')),
('Flacq District', (SELECT id FROM countries WHERE code = 'MU')),
('Grand Port District', (SELECT id FROM countries WHERE code = 'MU')),
('Moka District', (SELECT id FROM countries WHERE code = 'MU')),
('Pamplemousses District', (SELECT id FROM countries WHERE code = 'MU')),
-- Mexico
('Aguascalientes', (SELECT id FROM countries WHERE code = 'MX')),
('Baja California', (SELECT id FROM countries WHERE code = 'MX')),
('Baja California Sur', (SELECT id FROM countries WHERE code = 'MX')),
('Campeche', (SELECT id FROM countries WHERE code = 'MX')),
('Chiapas', (SELECT id FROM countries WHERE code = 'MX')),
-- Moldova
('Anenii Noi District', (SELECT id FROM countries WHERE code = 'MD')),
('Bălți Municipality', (SELECT id FROM countries WHERE code = 'MD')),
('Basarabeasca District', (SELECT id FROM countries WHERE code = 'MD')),
('Bender Municipality', (SELECT id FROM countries WHERE code = 'MD')),
('Briceni District', (SELECT id FROM countries WHERE code = 'MD')),
-- Monaco
('Fontvieille', (SELECT id FROM countries WHERE code = 'MC')),
('La Condamine', (SELECT id FROM countries WHERE code = 'MC')),
('Monaco-Ville', (SELECT id FROM countries WHERE code = 'MC')),
('Monte Carlo', (SELECT id FROM countries WHERE code = 'MC')),
-- Mongolia
('Arkhangai Province', (SELECT id FROM countries WHERE code = 'MN')),
('Bayan-Ölgii Province', (SELECT id FROM countries WHERE code = 'MN')),
('Bayankhongor Province', (SELECT id FROM countries WHERE code = 'MN')),
('Bulgan Province', (SELECT id FROM countries WHERE code = 'MN')),
('Darkhan-Uul Province', (SELECT id FROM countries WHERE code = 'MN')),
-- Montenegro
('Andrijevica Municipality', (SELECT id FROM countries WHERE code = 'ME')),
('Bar Municipality', (SELECT id FROM countries WHERE code = 'ME')),
('Berane Municipality', (SELECT id FROM countries WHERE code = 'ME')),
('Bijelo Polje Municipality', (SELECT id FROM countries WHERE code = 'ME')),
('Budva Municipality', (SELECT id FROM countries WHERE code = 'ME')),
-- Morocco
('Al Haouz Province', (SELECT id FROM countries WHERE code = 'MA')),
('Al Hoceima Province', (SELECT id FROM countries WHERE code = 'MA')),
('Azilal Province', (SELECT id FROM countries WHERE code = 'MA')),
('Ben Slimane Province', (SELECT id FROM countries WHERE code = 'MA')),
('Beni Mellal Province', (SELECT id FROM countries WHERE code = 'MA')),
-- Mozambique
('Cabo Delgado Province', (SELECT id FROM countries WHERE code = 'MZ')),
('Gaza Province', (SELECT id FROM countries WHERE code = 'MZ')),
('Inhambane Province', (SELECT id FROM countries WHERE code = 'MZ')),
('Maputo Province', (SELECT id FROM countries WHERE code = 'MZ')),
('Nampula Province', (SELECT id FROM countries WHERE code = 'MZ')),
-- Myanmar (Burma)
('Ayeyarwady Region', (SELECT id FROM countries WHERE code = 'MM')),
('Bago Region', (SELECT id FROM countries WHERE code = 'MM')),
('Chin State', (SELECT id FROM countries WHERE code = 'MM')),
('Kachin State', (SELECT id FROM countries WHERE code = 'MM')),
('Kayah State', (SELECT id FROM countries WHERE code = 'MM')),
-- Namibia
('Erongo Region', (SELECT id FROM countries WHERE code = 'NA')),
('Hardap Region', (SELECT id FROM countries WHERE code = 'NA')),
('Karas Region', (SELECT id FROM countries WHERE code = 'NA')),
('Kavango East Region', (SELECT id FROM countries WHERE code = 'NA')),
('Kavango West Region', (SELECT id FROM countries WHERE code = 'NA')),
-- Nauru
('Aiwo District', (SELECT id FROM countries WHERE code = 'NR')),
('Anabar District', (SELECT id FROM countries WHERE code = 'NR')),
('Anetan District', (SELECT id FROM countries WHERE code = 'NR')),
('Anibare District', (SELECT id FROM countries WHERE code = 'NR')),
('Baiti District', (SELECT id FROM countries WHERE code = 'NR')),
-- Nepal
('Bagmati Zone', (SELECT id FROM countries WHERE code = 'NP')),
('Bheri Zone', (SELECT id FROM countries WHERE code = 'NP')),
('Dhawalagiri Zone', (SELECT id FROM countries WHERE code = 'NP')),
('Gandaki Zone', (SELECT id FROM countries WHERE code = 'NP')),
('Janakpur Zone', (SELECT id FROM countries WHERE code = 'NP')),
-- Netherlands
('Drenthe', (SELECT id FROM countries WHERE code = 'NL')),
('Flevoland', (SELECT id FROM countries WHERE code = 'NL')),
('Friesland', (SELECT id FROM countries WHERE code = 'NL')),
('Gelderland', (SELECT id FROM countries WHERE code = 'NL')),
('Groningen', (SELECT id FROM countries WHERE code = 'NL')),
-- New Zealand
('Auckland', (SELECT id FROM countries WHERE code = 'NZ')),
('Bay of Plenty Region', (SELECT id FROM countries WHERE code = 'NZ')),
('Canterbury Region', (SELECT id FROM countries WHERE code = 'NZ')),
('Chatham Islands', (SELECT id FROM countries WHERE code = 'NZ')),
('Gisborne District', (SELECT id FROM countries WHERE code = 'NZ')),
-- Nicaragua
('Boaco', (SELECT id FROM countries WHERE code = 'NI')),
('Carazo', (SELECT id FROM countries WHERE code = 'NI')),
('Chinandega', (SELECT id FROM countries WHERE code = 'NI')),
('Chontales', (SELECT id FROM countries WHERE code = 'NI')),
('Estelí', (SELECT id FROM countries WHERE code = 'NI')),
-- Niger
('Agadez Region', (SELECT id FROM countries WHERE code = 'NE')),
('Diffa Region', (SELECT id FROM countries WHERE code = 'NE')),
('Dosso Region', (SELECT id FROM countries WHERE code = 'NE')),
('Maradi Region', (SELECT id FROM countries WHERE code = 'NE')),
('Tahoua Region', (SELECT id FROM countries WHERE code = 'NE')),
-- Nigeria
('Abia State', (SELECT id FROM countries WHERE code = 'NG')),
('Adamawa State', (SELECT id FROM countries WHERE code = 'NG')),
('Akwa Ibom State', (SELECT id FROM countries WHERE code = 'NG')),
('Anambra State', (SELECT id FROM countries WHERE code = 'NG')),
('Bauchi State', (SELECT id FROM countries WHERE code = 'NG')),
-- North Macedonia
('Aračinovo Municipality', (SELECT id FROM countries WHERE code = 'MK')),
('Berovo Municipality', (SELECT id FROM countries WHERE code = 'MK')),
('Bitola Municipality', (SELECT id FROM countries WHERE code = 'MK')),
('Bogovinje Municipality', (SELECT id FROM countries WHERE code = 'MK')),
('Bogdanci Municipality', (SELECT id FROM countries WHERE code = 'MK')),
-- Norway
('Akershus', (SELECT id FROM countries WHERE code = 'NO')),
('Aust-Agder', (SELECT id FROM countries WHERE code = 'NO')),
('Buskerud', (SELECT id FROM countries WHERE code = 'NO')),
('Finnmark', (SELECT id FROM countries WHERE code = 'NO')),
('Hedmark', (SELECT id FROM countries WHERE code = 'NO')),
-- Oman
('Ad Dakhiliyah Governorate', (SELECT id FROM countries WHERE code = 'OM')),
('Ad Dhahirah Governorate', (SELECT id FROM countries WHERE code = 'OM')),
('Al Batinah North Governorate', (SELECT id FROM countries WHERE code = 'OM')),
('Al Batinah South Governorate', (SELECT id FROM countries WHERE code = 'OM')),
('Al Buraimi Governorate', (SELECT id FROM countries WHERE code = 'OM')),
-- Pakistan
('Azad Kashmir', (SELECT id FROM countries WHERE code = 'PK')),
('Balochistan', (SELECT id FROM countries WHERE code = 'PK')),
('Federally Administered Tribal Areas', (SELECT id FROM countries WHERE code = 'PK')),
('Gilgit-Baltistan', (SELECT id FROM countries WHERE code = 'PK')),
('Islamabad Capital Territory', (SELECT id FROM countries WHERE code = 'PK')),
-- Palau
('Aimeliik', (SELECT id FROM countries WHERE code = 'PW')),
('Airai', (SELECT id FROM countries WHERE code = 'PW')),
('Angaur', (SELECT id FROM countries WHERE code = 'PW')),
('Hatohobei', (SELECT id FROM countries WHERE code = 'PW')),
('Kayangel', (SELECT id FROM countries WHERE code = 'PW')),
-- Panama
('Bocas del Toro Province', (SELECT id FROM countries WHERE code = 'PA')),
('Chiriquí Province', (SELECT id FROM countries WHERE code = 'PA')),
('Coclé Province', (SELECT id FROM countries WHERE code = 'PA')),
('Colón Province', (SELECT id FROM countries WHERE code = 'PA')),
('Darién Province', (SELECT id FROM countries WHERE code = 'PA')),
-- Papua New Guinea
('Bougainville', (SELECT id FROM countries WHERE code = 'PG')),
('Central Province', (SELECT id FROM countries WHERE code = 'PG')),
('Chimbu Province', (SELECT id FROM countries WHERE code = 'PG')),
('East New Britain Province', (SELECT id FROM countries WHERE code = 'PG')),
('East Sepik Province', (SELECT id FROM countries WHERE code = 'PG')),
-- Paraguay
('Alto Paraguay Department', (SELECT id FROM countries WHERE code = 'PY')),
('Alto Paraná Department', (SELECT id FROM countries WHERE code = 'PY')),
('Amambay Department', (SELECT id FROM countries WHERE code = 'PY')),
('Boquerón Department', (SELECT id FROM countries WHERE code = 'PY')),
('Caaguazú', (SELECT id FROM countries WHERE code = 'PY')),
-- Peru
('Amazonas Region', (SELECT id FROM countries WHERE code = 'PE')),
('Apurímac Region', (SELECT id FROM countries WHERE code = 'PE')),
('Arequipa Region', (SELECT id FROM countries WHERE code = 'PE')),
('Ayacucho Region', (SELECT id FROM countries WHERE code = 'PE')),
('Cajamarca Region', (SELECT id FROM countries WHERE code = 'PE')),
-- Philippines
('Abra', (SELECT id FROM countries WHERE code = 'PH')),
('Agusan del Norte', (SELECT id FROM countries WHERE code = 'PH')),
('Agusan del Sur', (SELECT id FROM countries WHERE code = 'PH')),
('Aklan', (SELECT id FROM countries WHERE code = 'PH')),
('Albay', (SELECT id FROM countries WHERE code = 'PH')),
-- Poland
('Greater Poland Voivodeship', (SELECT id FROM countries WHERE code = 'PL')),
('Kuyavian-Pomeranian Voivodeship', (SELECT id FROM countries WHERE code = 'PL')),
('Lesser Poland Voivodeship', (SELECT id FROM countries WHERE code = 'PL')),
('Lower Silesian Voivodeship', (SELECT id FROM countries WHERE code = 'PL')),
('Lublin Voivodeship', (SELECT id FROM countries WHERE code = 'PL')),
-- Portugal
('Aveiro', (SELECT id FROM countries WHERE code = 'PT')),
('Azores', (SELECT id FROM countries WHERE code = 'PT')),
('Beja', (SELECT id FROM countries WHERE code = 'PT')),
('Braga', (SELECT id FROM countries WHERE code = 'PT')),
('Bragança', (SELECT id FROM countries WHERE code = 'PT')),
-- Qatar
('Al Daayen Municipality', (SELECT id FROM countries WHERE code = 'QA')),
('Al Khor Municipality', (SELECT id FROM countries WHERE code = 'QA')),
('Al Rayyan Municipality', (SELECT id FROM countries WHERE code = 'QA')),
('Al Wakrah Municipality', (SELECT id FROM countries WHERE code = 'QA')),
('Umm Salal Municipality', (SELECT id FROM countries WHERE code = 'QA')),
-- Romania
('Alba County', (SELECT id FROM countries WHERE code = 'RO')),
('Arad County', (SELECT id FROM countries WHERE code = 'RO')),
('Arges County', (SELECT id FROM countries WHERE code = 'RO')),
('Bacau County', (SELECT id FROM countries WHERE code = 'RO')),
('Bihor County', (SELECT id FROM countries WHERE code = 'RO')),
-- Russia
('Adygea', (SELECT id FROM countries WHERE code = 'RU')),
('Altai Krai', (SELECT id FROM countries WHERE code = 'RU')),
('Altai Republic', (SELECT id FROM countries WHERE code = 'RU')),
('Amur Oblast', (SELECT id FROM countries WHERE code = 'RU')),
('Arkhangelsk Oblast', (SELECT id FROM countries WHERE code = 'RU')),
-- Rwanda
('Eastern Province', (SELECT id FROM countries WHERE code = 'RW')),
('Kigali Province', (SELECT id FROM countries WHERE code = 'RW')),
('Northern Province', (SELECT id FROM countries WHERE code = 'RW')),
('Southern Province', (SELECT id FROM countries WHERE code = 'RW')),
('Western Province', (SELECT id FROM countries WHERE code = 'RW')),
-- Saint Kitts and Nevis
('Christ Church Nichola Town Parish', (SELECT id FROM countries WHERE code = 'KN')),
('Saint Anne Sandy Point Parish', (SELECT id FROM countries WHERE code = 'KN')),
('Saint George Basseterre Parish', (SELECT id FROM countries WHERE code = 'KN')),
('Saint George Gingerland Parish', (SELECT id FROM countries WHERE code = 'KN')),
('Saint James Windward Parish', (SELECT id FROM countries WHERE code = 'KN')),
-- Saint Lucia
('Anse la Raye Quarter', (SELECT id FROM countries WHERE code = 'LC')),
('Castries Quarter', (SELECT id FROM countries WHERE code = 'LC')),
('Choiseul Quarter', (SELECT id FROM countries WHERE code = 'LC')),
('Dennery Quarter', (SELECT id FROM countries WHERE code = 'LC')),
('Gros Islet Quarter', (SELECT id FROM countries WHERE code = 'LC')),
-- Saint Vincent and the Grenadines
('Charlotte Parish', (SELECT id FROM countries WHERE code = 'VC')),
('Grenadines Parish', (SELECT id FROM countries WHERE code = 'VC')),
('Saint Andrew Parish', (SELECT id FROM countries WHERE code = 'VC')),
('Saint David Parish', (SELECT id FROM countries WHERE code = 'VC')),
('Saint George Parish', (SELECT id FROM countries WHERE code = 'VC')),
-- Samoa
('Aiga-i-le-Tai', (SELECT id FROM countries WHERE code = 'WS')),
('Atua', (SELECT id FROM countries WHERE code = 'WS')),
('Fa'asaleleaga', (SELECT id FROM countries WHERE code = 'WS')),
('Gaga'emauga', (SELECT id FROM countries WHERE code = 'WS')),
('Gaga ifomauga', (SELECT id FROM countries WHERE code = 'WS')),
-- San Marino
('Acquaviva', (SELECT id FROM countries WHERE code = 'SM')),
('Borgo Maggiore', (SELECT id FROM countries WHERE code = 'SM')),
('Chiesanuova', (SELECT id FROM countries WHERE code = 'SM')),
('Domagnano', (SELECT id FROM countries WHERE code = 'SM')),
('Faetano', (SELECT id FROM countries WHERE code = 'SM')),
-- São Tomé and Príncipe
('Cantagalo', (SELECT id FROM countries WHERE code = 'ST')),
('Caué District', (SELECT id FROM countries WHERE code = 'ST')),
('Lembá District', (SELECT id FROM countries WHERE code = 'ST')),
('Lobata District', (SELECT id FROM countries WHERE code = 'ST')),
('Mé-Zóchi District', (SELECT id FROM countries WHERE code = 'ST')),
-- Saudi Arabia
('Al Bahah Region', (SELECT id FROM countries WHERE code = 'SA')),
('Al Jawf Region', (SELECT id FROM countries WHERE code = 'SA')),
('Al Madinah Region', (SELECT id FROM countries WHERE code = 'SA')),
('Al-Qassim Region', (SELECT id FROM countries WHERE code = 'SA')),
('Ar Riyad Region', (SELECT id FROM countries WHERE code = 'SA')),
-- Senegal
('Dakar Region', (SELECT id FROM countries WHERE code = 'SN')),
('Diourbel Region', (SELECT id FROM countries WHERE code = 'SN')),
('Fatick Region', (SELECT id FROM countries WHERE code = 'SN')),
('Kaffrine Region', (SELECT id FROM countries WHERE code = 'SN')),
('Kaolack Region', (SELECT id FROM countries WHERE code = 'SN')),
-- Serbia
('Belgrade', (SELECT id FROM countries WHERE code = 'RS')),
('Bor District', (SELECT id FROM countries WHERE code = 'RS')),
('Braničevo District', (SELECT id FROM countries WHERE code = 'RS')),
('Central Banat District', (SELECT id FROM countries WHERE code = 'RS')),
('Jablanica District', (SELECT id FROM countries WHERE code = 'RS')),
-- Seychelles
('Anse aux Pins', (SELECT id FROM countries WHERE code = 'SC')),
('Anse Boileau', (SELECT id FROM countries WHERE code = 'SC')),
('Anse Etoile', (SELECT id FROM countries WHERE code = 'SC')),
('Anse Royale', (SELECT id FROM countries WHERE code = 'SC')),
('Au Cap', (SELECT id FROM countries WHERE code = 'SC')),
-- Sierra Leone
('Eastern Province', (SELECT id FROM countries WHERE code = 'SL')),
('Northern Province', (SELECT id FROM countries WHERE code = 'SL')),
('Southern Province', (SELECT id FROM countries WHERE code = 'SL')),
('Western Area', (SELECT id FROM countries WHERE code = 'SL')),
-- Singapore
('Central Region', (SELECT id FROM countries WHERE code = 'SG')),
-- Slovakia
('Banská Bystrica Region', (SELECT id FROM countries WHERE code = 'SK')),
('Bratislava Region', (SELECT id FROM countries WHERE code = 'SK')),
('Košice Region', (SELECT id FROM countries WHERE code = 'SK')),
('Nitra Region', (SELECT id FROM countries WHERE code = 'SK')),
('Prešov Region', (SELECT id FROM countries WHERE code = 'SK')),
-- Slovenia
('Carinthia', (SELECT id FROM countries WHERE code = 'SI')),
('Central Slovenia', (SELECT id FROM countries WHERE code = 'SI')),
('Coastal–Karst', (SELECT id FROM countries WHERE code = 'SI')),
('Gorizia', (SELECT id FROM countries WHERE code = 'SI')),
('Littoral–Inner Carniola', (SELECT id FROM countries WHERE code = 'SI')),
-- Solomon Islands
('Central Province', (SELECT id FROM countries WHERE code = 'SB')),
('Choiseul Province', (SELECT id FROM countries WHERE code = 'SB')),
('Guadalcanal Province', (SELECT id FROM countries WHERE code = 'SB')),
('Honiara Town', (SELECT id FROM countries WHERE code = 'SB')),
('Isabel Province', (SELECT id FROM countries WHERE code = 'SB')),
-- Somalia
('Awdal', (SELECT id FROM countries WHERE code = 'SO')),
('Bakool', (SELECT id FROM countries WHERE code = 'SO')),
('Banaadir', (SELECT id FROM countries WHERE code = 'SO')),
('Bari', (SELECT id FROM countries WHERE code = 'SO')),
('Bay', (SELECT id FROM countries WHERE code = 'SO')),
-- South Africa
('Eastern Cape', (SELECT id FROM countries WHERE code = 'ZA')),
('Free State', (SELECT id FROM countries WHERE code = 'ZA')),
('Gauteng', (SELECT id FROM countries WHERE code = 'ZA')),
('KwaZulu-Natal', (SELECT id FROM countries WHERE code = 'ZA')),
('Limpopo', (SELECT id FROM countries WHERE code = 'ZA')),
-- South Korea
('Busan', (SELECT id FROM countries WHERE code = 'KR')),
('Daegu', (SELECT id FROM countries WHERE code = 'KR')),
('Daejeon', (SELECT id FROM countries WHERE code = 'KR')),
('Gangwon Province', (SELECT id FROM countries WHERE code = 'KR')),
('Gwangju', (SELECT id FROM countries WHERE code = 'KR')),
-- South Sudan
('Central Equatoria', (SELECT id FROM countries WHERE code = 'SS')),
('Eastern Equatoria', (SELECT id FROM countries WHERE code = 'SS')),
('Jonglei', (SELECT id FROM countries WHERE code = 'SS')),
('Lakes', (SELECT id FROM countries WHERE code = 'SS')),
('Unity', (SELECT id FROM countries WHERE code = 'SS')),
-- Spain
('Andalusia', (SELECT id FROM countries WHERE code = 'ES')),
('Aragon', (SELECT id FROM countries WHERE code = 'ES')),
('Asturias', (SELECT id FROM countries WHERE code = 'ES')),
('Balearic Islands', (SELECT id FROM countries WHERE code = 'ES')),
('Basque Country', (SELECT id FROM countries WHERE code = 'ES')),
-- Sri Lanka
('Central Province', (SELECT id FROM countries WHERE code = 'LK')),
('Eastern Province', (SELECT id FROM countries WHERE code = 'LK')),
('Northern Province', (SELECT id FROM countries WHERE code = 'LK')),
('North Central Province', (SELECT id FROM countries WHERE code = 'LK')),
('North Western Province', (SELECT id FROM countries WHERE code = 'LK')),
-- Sudan
('Blue Nile', (SELECT id FROM countries WHERE code = 'SD')),
('Central Darfur', (SELECT id FROM countries WHERE code = 'SD')),
('East Darfur', (SELECT id FROM countries WHERE code = 'SD')),
('Kassala', (SELECT id FROM countries WHERE code = 'SD')),
('North Darfur', (SELECT id FROM countries WHERE code = 'SD')),
-- Suriname
('Brokopondo District', (SELECT id FROM countries WHERE code = 'SR')),
('Commewijne District', (SELECT id FROM countries WHERE code = 'SR')),
('Coronie District', (SELECT id FROM countries WHERE code = 'SR')),
('Marowijne District', (SELECT id FROM countries WHERE code = 'SR')),
('Nickerie District', (SELECT id FROM countries WHERE code = 'SR')),
-- Sweden
('Blekinge County', (SELECT id FROM countries WHERE code = 'SE')),
('Dalarna County', (SELECT id FROM countries WHERE code = 'SE')),
('Gotland County', (SELECT id FROM countries WHERE code = 'SE')),
('Gävleborg County', (SELECT id FROM countries WHERE code = 'SE')),
('Halland County', (SELECT id FROM countries WHERE code = 'SE')),
-- Switzerland
('Aargau', (SELECT id FROM countries WHERE code = 'CH')),
('Appenzell Ausserrhoden', (SELECT id FROM countries WHERE code = 'CH')),
('Appenzell Innerrhoden', (SELECT id FROM countries WHERE code = 'CH')),
('Basel-Landschaft', (SELECT id FROM countries WHERE code = 'CH')),
('Basel-Stadt', (SELECT id FROM countries WHERE code = 'CH')),
-- Syria
('Al-Hasakah Governorate', (SELECT id FROM countries WHERE code = 'SY')),
('Al-Raqqah Governorate', (SELECT id FROM countries WHERE code = 'SY')),
('As-Suwayda Governorate', (SELECT id FROM countries WHERE code = 'SY')),
('Damascus Governorate', (SELECT id FROM countries WHERE code = 'SY')),
('Daraa Governorate', (SELECT id FROM countries WHERE code = 'SY')),
-- Taiwan
('Changhua County', (SELECT id FROM countries WHERE code = 'TW')),
('Chiayi City', (SELECT id FROM countries WHERE code = 'TW')),
('Chiayi County', (SELECT id FROM countries WHERE code = 'TW')),
('Hsinchu City', (SELECT id FROM countries WHERE code = 'TW')),
('Hsinchu County', (SELECT id FROM countries WHERE code = 'TW')),
-- Tajikistan
('Dushanbe', (SELECT id FROM countries WHERE code = 'TJ')),
('GBAO', (SELECT id FROM countries WHERE code = 'TJ')),
('Khatlon Region', (SELECT id FROM countries WHERE code = 'TJ')),
('Sughd Region', (SELECT id FROM countries WHERE code = 'TJ')),
-- Tanzania
('Arusha Region', (SELECT id FROM countries WHERE code = 'TZ')),
('Dar es Salaam Region', (SELECT id FROM countries WHERE code = 'TZ')),
('Dodoma Region', (SELECT id FROM countries WHERE code = 'TZ')),
('Iringa Region', (SELECT id FROM countries WHERE code = 'TZ')),
('Kagera Region', (SELECT id FROM countries WHERE code = 'TZ')),
-- Thailand
('Amnat Charoen Province', (SELECT id FROM countries WHERE code = 'TH')),
('Ang Thong Province', (SELECT id FROM countries WHERE code = 'TH')),
('Bangkok', (SELECT id FROM countries WHERE code = 'TH')),
('Bueng Kan Province', (SELECT id FROM countries WHERE code = 'TH')),
('Buri Ram Province', (SELECT id FROM countries WHERE code = 'TH')),
-- Timor-Leste
('Aileu Municipality', (SELECT id FROM countries WHERE code = 'TL')),
('Ainaro Municipality', (SELECT id FROM countries WHERE code = 'TL')),
('Baucau Municipality', (SELECT id FROM countries WHERE code = 'TL')),
('Bobonaro Municipality', (SELECT id FROM countries WHERE code = 'TL')),
('Cova Lima Municipality', (SELECT id FROM countries WHERE code = 'TL')),
-- Togo
('Centrale Region', (SELECT id FROM countries WHERE code = 'TG')),
('Kara Region', (SELECT id FROM countries WHERE code = 'TG')),
('Maritime Region', (SELECT id FROM countries WHERE code = 'TG')),
('Plateaux Region', (SELECT id FROM countries WHERE code = 'TG')),
('Savanes Region', (SELECT id FROM countries WHERE code = 'TG')),
-- Tonga
('Eua', (SELECT id FROM countries WHERE code = 'TO')),
('Haapai', (SELECT id FROM countries WHERE code = 'TO')),
('Niuas', (SELECT id FROM countries WHERE code = 'TO')),
('Tongatapu', (SELECT id FROM countries WHERE code = 'TO')),
('Vava u', (SELECT id FROM countries WHERE code = 'TO')),
-- Trinidad and Tobago
('Arima', (SELECT id FROM countries WHERE code = 'TT')),
('Chaguanas', (SELECT id FROM countries WHERE code = 'TT')),
('Couva-Tabaquite-Talparo', (SELECT id FROM countries WHERE code = 'TT')),
('Diego Martin', (SELECT id FROM countries WHERE code = 'TT')),
('Eastern Tobago', (SELECT id FROM countries WHERE code = 'TT')),
-- Tunisia
('Ariana Governorate', (SELECT id FROM countries WHERE code = 'TN')),
('Ben Arous Governorate', (SELECT id FROM countries WHERE code = 'TN')),
('Bizerte Governorate', (SELECT id FROM countries WHERE code = 'TN')),
('Gabès Governorate', (SELECT id FROM countries WHERE code = 'TN')),
('Gafsa Governorate', (SELECT id FROM countries WHERE code = 'TN')),
-- Turkey
('Adana Province', (SELECT id FROM countries WHERE code = 'TR')),
('Adıyaman Province', (SELECT id FROM countries WHERE code = 'TR')),
('Afyonkarahisar Province', (SELECT id FROM countries WHERE code = 'TR')),
('Ağrı Province', (SELECT id FROM countries WHERE code = 'TR')),
('Aksaray Province', (SELECT id FROM countries WHERE code = 'TR')),
-- Turkmenistan
('Ahal Region', (SELECT id FROM countries WHERE code = 'TM')),
('Balkan Region', (SELECT id FROM countries WHERE code = 'TM')),
('Daşoguz Region', (SELECT id FROM countries WHERE code = 'TM')),
('Lebap Region', (SELECT id FROM countries WHERE code = 'TM')),
('Mary Region', (SELECT id FROM countries WHERE code = 'TM')),
-- Tuvalu
('Funafuti', (SELECT id FROM countries WHERE code = 'TV')),
-- Uganda
('Central Region', (SELECT id FROM countries WHERE code = 'UG')),
('Eastern Region', (SELECT id FROM countries WHERE code = 'UG')),
('Northern Region', (SELECT id FROM countries WHERE code = 'UG')),
('Western Region', (SELECT id FROM countries WHERE code = 'UG')),
-- Ukraine
('Cherkasy Oblast', (SELECT id FROM countries WHERE code = 'UA')),
('Chernihiv Oblast', (SELECT id FROM countries WHERE code = 'UA')),
('Chernivtsi Oblast', (SELECT id FROM countries WHERE code = 'UA')),
('Dnipropetrovsk Oblast', (SELECT id FROM countries WHERE code = 'UA')),
('Donetsk Oblast', (SELECT id FROM countries WHERE code = 'UA')),
-- United Arab Emirates
('Abu Dhabi Emirate', (SELECT id FROM countries WHERE code = 'AE')),
('Ajman Emirate', (SELECT id FROM countries WHERE code = 'AE')),
('Dubai Emirate', (SELECT id FROM countries WHERE code = 'AE')),
('Fujairah Emirate', (SELECT id FROM countries WHERE code = 'AE')),
('Ras al-Khaimah Emirate', (SELECT id FROM countries WHERE code = 'AE')),
-- United Kingdom
('England', (SELECT id FROM countries WHERE code = 'GB')),
('Northern Ireland', (SELECT id FROM countries WHERE code = 'GB')),
('Scotland', (SELECT id FROM countries WHERE code = 'GB')),
('Wales', (SELECT id FROM countries WHERE code = 'GB')),
-- United States
('Alabama', (SELECT id FROM countries WHERE code = 'US')),
('Alaska', (SELECT id FROM countries WHERE code = 'US')),
('American Samoa', (SELECT id FROM countries WHERE code = 'US')),
('Arizona', (SELECT id FROM countries WHERE code = 'US')),
('Arkansas', (SELECT id FROM countries WHERE code = 'US')),
-- Uruguay
('Artigas Department', (SELECT id FROM countries WHERE code = 'UY')),
('Canelones Department', (SELECT id FROM countries WHERE code = 'UY')),
('Cerro Largo Department', (SELECT id FROM countries WHERE code = 'UY')),
('Colonia Department', (SELECT id FROM countries WHERE code = 'UY')),
('Durazno Department', (SELECT id FROM countries WHERE code = 'UY')),
-- Uzbekistan
('Andijan Region', (SELECT id FROM countries WHERE code = 'UZ')),
('Bukhara Region', (SELECT id FROM countries WHERE code = 'UZ')),
('Fergana Region', (SELECT id FROM countries WHERE code = 'UZ')),
('Jizzakh Region', (SELECT id FROM countries WHERE code = 'UZ')),
('Karakalpakstan', (SELECT id FROM countries WHERE code = 'UZ')),
-- Vanuatu
('Malampa', (SELECT id FROM countries WHERE code = 'VU')),
('Penama', (SELECT id FROM countries WHERE code = 'VU')),
('Sanma', (SELECT id FROM countries WHERE code = 'VU')),
('Shefa', (SELECT id FROM countries WHERE code = 'VU')),
('Tafea', (SELECT id FROM countries WHERE code = 'VU')),
-- Vatican City
('Vatican City', (SELECT id FROM countries WHERE code = 'VA')),
-- Venezuela
('Amazonas', (SELECT id FROM countries WHERE code = 'VE')),
('Anzoátegui', (SELECT id FROM countries WHERE code = 'VE')),
('Apure', (SELECT id FROM countries WHERE code = 'VE')),
('Aragua', (SELECT id FROM countries WHERE code = 'VE')),
('Barinas', (SELECT id FROM countries WHERE code = 'VE')),
-- Vietnam
('An Giang', (SELECT id FROM countries WHERE code = 'VN')),
('Bắc Giang', (SELECT id FROM countries WHERE code = 'VN')),
('Bắc Kạn', (SELECT id FROM countries WHERE code = 'VN')),
('Bạc Liêu', (SELECT id FROM countries WHERE code = 'VN')),
('Bắc Ninh', (SELECT id FROM countries WHERE code = 'VN')),
-- Yemen
('Abyan Governorate', (SELECT id FROM countries WHERE code = 'YE')),
('Aden Governorate', (SELECT id FROM countries WHERE code = 'YE')),
('Al Bayda Governorate', (SELECT id FROM countries WHERE code = 'YE')),
('Al Hudaydah Governorate', (SELECT id FROM countries WHERE code = 'YE')),
('Al Jawf Governorate', (SELECT id FROM countries WHERE code = 'YE')),
-- Zambia
('Central Province', (SELECT id FROM countries WHERE code = 'ZM')),
('Copperbelt Province', (SELECT id FROM countries WHERE code = 'ZM')),
('Eastern Province', (SELECT id FROM countries WHERE code = 'ZM')),
('Luapula Province', (SELECT id FROM countries WHERE code = 'ZM')),
('Lusaka Province', (SELECT id FROM countries WHERE code = 'ZM')),
-- Zimbabwe
('Bulawayo', (SELECT id FROM countries WHERE code = 'ZW')),
('Harare', (SELECT id FROM countries WHERE code = 'ZW')),
('Manicaland', (SELECT id FROM countries WHERE code = 'ZW')),
('Mashonaland Central', (SELECT id FROM countries WHERE code = 'ZW')),
('Matabeleland South', (SELECT id FROM countries WHERE code = 'ZW'));
